name: .NET


on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x 
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/
      - uses: codecov/codecov-action@v1
        with:
          token: acefca5d-53b1-4a10-b52b-92c68507064a
          files: ./test/CalculatorLibraryTests/TestResults/coverage.opencover.xml,./test/Calculator.Tests/TestResults/coverage.opencover.xml
          flags: unittests 
          name: codecov-umbrella
          fail_ci_if_error: true 
          verbose: true
